<a href="https://colab.research.google.com/github/sharon-nasimiyu/2022WebProject/blob/main/Untitled16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
#Installation of beautiful soup which will be used in extraction of data
!pip3 install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

In [54]:
#importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import re
import time
from datetime import datetime
import matplotlib.dates as mdates
import matplotlib.ticker as ticker
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests

In [55]:
#scrapping the best selling books in amazon which are updated hourly and most of them are the lately reviewed and trending books
no_pages = 2

def get_data(pageNo):  
    headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    r = requests.get('https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_pg_'+str(pageNo)+'?ie=UTF8&pg='+str(pageNo), headers=headers)#, proxies=proxies)
    content = r.content
    soup = BeautifulSoup(content)
    #print(soup)

    alls = []
    for d in soup.findAll('div', attrs={'class':'a-section a-spacing-none aok-relative'}):
        #print(d)
        name = d.find('span', attrs={'class':'zg-text-center-align'})
        n = name.find_all('img', alt=True)
        #print(n[0]['alt'])
        author = d.find('a', attrs={'class':'a-size-small a-link-child'})
        rating = d.find('span', attrs={'class':'a-icon-alt'})
        users_rated = d.find('a', attrs={'class':'a-size-small a-link-normal'})
        price = d.find('span', attrs={'class':'p13n-sc-price'})

        all1=[]

        if name is not None:
            #print(n[0]['alt'])
            all1.append(n[0]['alt'])
        else:
            all1.append("unknown-product")

        if author is not None:
            #print(author.text)
            all1.append(author.text)
        elif author is None:
            author = d.find('span', attrs={'class':'a-size-small a-color-base'})
            if author is not None:
                all1.append(author.text)
            else:    
                all1.append('0')

        if rating is not None:
            #print(rating.text)
            all1.append(rating.text)
        else:
            all1.append('-1')

        if users_rated is not None:
            #print(price.text)
            all1.append(users_rated.text)
        else:
            all1.append('0')     

        if price is not None:
            #print(price.text)
            all1.append(price.text)
        else:
            all1.append('0')
        alls.append(all1)    
    return alls

In [56]:
#saving the extracted data frame as csv file
results = []
for i in range(1, no_pages+1):
    results.append(get_data(i))
flatten = lambda l: [item for sublist in l for item in sublist]
df = pd.DataFrame(flatten(results),columns=['Book Name','Author','Rating','Customers_Rated', 'Price'])
df.to_csv('amazonlately_products.csv', index=False, encoding='utf-8')

In [57]:
#reading the savedv file
df = pd.read_csv("amazonlately_products.csv")
df.shape
(100, 5)
df.head(61)

                                            Book Name  ...    Price
0                             The Psychology of Money  ...  ₹240.00
1   Atomic Habits: The life-changing million copy ...  ...  ₹480.00
2                                        DO EPIC SHIT  ...  ₹298.00
3   Rich Dad Poor Dad: What the Rich Teach Their K...  ...  ₹243.00
4   My First Library: Boxset of 10 Board Books for...  ...  ₹349.00
5   Ikigai: The Japanese secret to a long and happ...  ...  ₹310.00
6                                Word Power Made Easy  ...   ₹92.00
7   Grandma's Bag of Stories: Collection of 20+ Il...  ...  ₹147.00
8   27 Years UPSC IAS/ IPS Prelims Topic-wise Solv...  ...  ₹351.00
9                                       The Alchemist  ...  ₹201.00
10  My First Book of Pencil Control : Practice Pat...  ...   ₹89.00
11                The Power of Your Subconscious Mind  ...  ₹125.00
12  The Almanack Of Naval Ravikant: A Guide to Wea...  ...  ₹232.00
13  Moral Story Books for Kids (Pack of 10 Books) ...  ...  ₹235.00
14  Oswaal CBSE Question Bank Chapterwise For Term...  ...  ₹809.00
15                                           400 Days  ...  ₹152.00
16  Quantitative Aptitude for Competitive Examinat...  ...  ₹467.00
17                     Spoken English Course (Telugu)  ...  ₹284.00
18                           It Ends With Us: A Novel  ...  ₹374.00
19           Very First Sight Words Sentences Level 1  ...  ₹110.00
20  The Subtle Art of Not Giving a F*ck: A Counter...  ...  ₹303.00
21  World’s Greatest Books For Personal Growth & W...  ...  ₹279.00
22  My First Mythology Tale (Illustrated) (Set of ...  ...  ₹191.00
23  Life's Amazing Secrets: How to Find Balance an...  ...  ₹214.00
24  Karma: A Yogi's Guide to Crafting Your Destiny...  ...  ₹148.00
25  Attitude Is Everything: Change Your Attitude ....  ...  ₹150.00
26  Eat That Frog!: 21 Great Ways to Stop Procrast...  ...  ₹146.00
27  Writing Practice Boxset: Pack of 4 Books (Writ...  ...  ₹159.00
28  Picture Books Collection for Early Learning (S...  ...  ₹220.00
29                          The Diary of a Young Girl  ...   ₹99.00
30                                  As a Man Thinketh  ...   ₹59.00
31  Rich Dad Poor Dad - 20Th Anniversary Edition -...  ...  ₹192.00
32                The Power of Your Subconscious Mind  ...   ₹99.00
33              Sapiens: A Brief History of Humankind  ...  ₹345.00
34                         The Richest Man in Babylon  ...   ₹99.00
35                             General Knowledge 2022  ...  ₹140.00
36                     Manorama English Yearbook 2022  ...  ₹288.00
37           Diary of a Wimpy Kid: Big Shot (Book 16)  ...  ₹185.00
38                      The Monk Who Sold His Ferrari  ...  ₹168.00
39  Colour With Crayons Book 1 for Kids Age 1 -6 Y...  ...   ₹49.00
40  The Intelligent Investor (English) Paperback –...  ...  ₹449.00
41  My First Complete Learning Library: Boxset of ...  ...  ₹669.00
42                                  General Knowledge  ...  ₹188.00
43  Indian Polity For Civil Services and Other Sta...  ...  ₹672.00
44                       Grandparents' Bag of Stories  ...  ₹158.00
45  Animals Tales From Panchtantra: Timeless Stori...  ...  ₹169.00
46  My First 1000 Words: Early Learning Picture Bo...  ...  ₹149.00
47  101 Panchatantra Stories for Children: Colourf...  ...  ₹135.00
48  Three Thousand Stitches: Ordinary People, Extr...  ...  ₹142.00
49  Brain Activity Book for Kids - 200+ Activities...  ...   ₹86.00

[50 rows x 5 columns]

In [58]:
#reprocessing the data and dropping some aspects such as we know that the rating is out of 5 so as we just remain with bare ratings
df['Rating'] = df['Rating'].apply(lambda x: x.split()[0])
df['Rating'] = pd.to_numeric(df['Rating'])
df["Price"] = df["Price"].str.replace('₹', '')
df["Price"] = df["Price"].str.replace(',', '')
df['Price'] = df['Price'].apply(lambda x: x.split('.')[0])
df['Price'] = df['Price'].astype(int)
df["Customers_Rated"] = df["Customers_Rated"].str.replace(',', '')
df['Customers_Rated'] = pd.to_numeric(df['Customers_Rated'], errors='ignore')
df.head()

                                           Book Name  ... Price
0                            The Psychology of Money  ...   240
1  Atomic Habits: The life-changing million copy ...  ...   480
2                                       DO EPIC SHIT  ...   298
3  Rich Dad Poor Dad: What the Rich Teach Their K...  ...   243
4  My First Library: Boxset of 10 Board Books for...  ...   349

[5 rows x 5 columns]

In [59]:
#Sorting the books with the most rated books which most likely will be among the latelty reviewed books
data = df.sort_values(["Customers_Rated"], axis=0, ascending=False)[:21]
data

                                            Book Name  ... Price
9                                       The Alchemist  ...   201
20  The Subtle Art of Not Giving a F*ck: A Counter...  ...   303
3   Rich Dad Poor Dad: What the Rich Teach Their K...  ...   243
11                The Power of Your Subconscious Mind  ...   125
32                The Power of Your Subconscious Mind  ...    99
4   My First Library: Boxset of 10 Board Books for...  ...   349
33              Sapiens: A Brief History of Humankind  ...   345
6                                Word Power Made Easy  ...    92
1   Atomic Habits: The life-changing million copy ...  ...   480
40  The Intelligent Investor (English) Paperback –...  ...   449
5   Ikigai: The Japanese secret to a long and happ...  ...   310
18                           It Ends With Us: A Novel  ...   374
34                         The Richest Man in Babylon  ...    99
0                             The Psychology of Money  ...   240
16  Quantitative Aptitude for Competitive Examinat...  ...   467
38                      The Monk Who Sold His Ferrari  ...   168
42                                  General Knowledge  ...   188
29                          The Diary of a Young Girl  ...    99
21  World’s Greatest Books For Personal Growth & W...  ...   279
25  Attitude Is Everything: Change Your Attitude ....  ...   150
10  My First Book of Pencil Control : Practice Pat...  ...    89

[21 rows x 5 columns]

# New Section